name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'davidson-consulting/tlpc-sensor'
          path: './tlpc-sensor'
      - uses: actions/checkout@v2
        with:
          repository: 'davidson-consulting/j-joules'
          path: './j-joules'
      - uses: actions/checkout@v2
        with:
          repository: 'davidson-consulting/junit-jjoules'
          path: './junit-jjoules'
      - name: Install TLPC-Sensor Java adapter
        run: mvn clean install -DskipTests -f tlpc-sensor/examples/tlpc-sensor/pom.xml
      - name: Install JJoules
        run: mvn clean install -DskipTests -f j-joules/pom.xml
      - name: Install JUnit-JJoules
        run: mvn clean install -DskipTests -f junit-jjoules/pom.xml
      - name: Build and run tests
        run: export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'` && echo "🎉 ${MAVEN_HOME}" && mvn --batch-mode clean install
      - name: SonarCloud Scan
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=davidson-consulting -Dsonar.projectKey=davidson-consulting_diff-jjoules -Dsonar.branch=main -Dsonar.sources=src/main/java/ -Dsonar.language=java -Dsonar.java.binaries=target/classes -Dcheckstyle.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
