name: Pull-Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'davidson-consulting/j-joules'
          path: './j-joules'
      - uses: actions/checkout@v2
        with:
          repository: 'davidson-consulting/junit-jjoules'
          path: './junit-jjoules'
      - name: Install JJoules
        run: mvn clean install -DskipTests -f j-joules/pom.xml
      - name: Install JUnit-JJoules
        run: mvn clean install -DskipTests -f junit-jjoules/pom.xml
      - name: Setup permission for RAPL
        run: sudo chmod -R 777 /sys/devices/virtual/powercap/intel-rapl/intel-rapl:*
      - name: Setup permission for perf
        run: sudo echo -1 > /proc/sys/kernel/perf_event_paranoid
      - name: Build and run tests
        run: export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'` && echo "🎉 ${MAVEN_HOME}" && mvn --batch-mode clean install -Dcheckstyle.skip=true
      - name: Codecov
        uses: codecov/codecov-action@v2